"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T12:38:49.478582+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, broadcast, lit
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                      .option("header", "true")
                       .option("inferSchema", "false")
                       .load(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))

    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                       .load(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))

    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
    transactions_df = transactions_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    transactions_df = transactions_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))

    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_df = transactions_df.dropDuplicates(["transaction_id"], ["ingestion_timestamp"]).orderBy("ingestion_timestamp", ascending=False)

    # Read merchants CSV and cache it
    merchants_df = (spark.read.format("csv")
                   .option("header", "true")
                    .option("inferSchema", "false")
                   .load(merchants_path))
    merchants_df = merchants_df.cache()

    # Join transactions with merchants on merchant_id to get merchant_name, category, city
    transactions_df = (transactions_df.join(broadcast(merchants_df), transactions_df.merchant_id == merchants_df.merchant_id, "left_outer")
                       .withColumn("quality_flag", 
                                   col("merchant_name").when(col("merchant_name").isNotNull(), "CLEAN").otherwise("UNMATCHED")))

    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize SparkSession
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())

    # Define paths and run metadata
    input_path = "s3://sigma-datatech/bronze/transactions.csv"
    merchants_path = "s3://sigma-datatech/bronze/merchants.csv"
    bronze_path = "s3://sigma-datatech/silver/transactions"
    silver_path = "s3://sigma-datatech/silver/transactions"
    run_date = "2026-05-27"
    run_id = "run_20260527"

    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)

    # Transform Silver layer
    transform_silver(spark, bronze_path, merchants_path, silver_path, run_date)

    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech/metadata/run_{run_date}.json", "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, avg, collect_set, coalesce, lit, mode
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType, IntegerType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txns")
        ) \
        .withColumn("failure_rate_pct", (col("failed_txns") / col("txn_count") * 100).cast(FloatType()))

    # Write to output path
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Calculate metrics
    customer_ltv_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            mode("payment_method").over(Window.partitionBy("customer_id")).alias("preferred_payment_method")
        )
    
    # Write to output path
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants")
        ) \
       .withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))

    # Write to output path
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths
    merchant_performance_output = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output = f"{gold_output_dir}/customer_ltv"
    daily_summary_output = f"{gold_output_dir}/daily_summary"

    # Run each gold layer function
    build_merchant_performance(spark, silver_path, merchant_performance_output, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_output)
    build_daily_summary(spark, silver_path, daily_summary_output, run_date)

    # Write run metadata summary
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "tables": ["merchant_performance", "customer_ltv", "daily_summary"]
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
