"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:49:46.786463+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
import csv
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from sample_data import SAMPLE_MERCHANTS, SAMPLE_TRANSACTIONS
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, lit, broadcast, row_number, when
from pyspark.sql.types import FloatType, DateType
from pyspark.sql.window import Window

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read CSV with all columns as strings
    bronze_df = spark.read.option("header", "true").option("inferSchema", "false").csv(input_path)
    
    # Add required columns
    bronze_df = bronze_df.withColumn("ingestion_timestamp", current_timestamp()) \
                          .withColumn("source_file", lit(input_path)) \
                         .withColumn("pipeline_run_id", lit(run_id))
    
    # Write Parquet partitioned by date
    bronze_df.write.mode("overwrite").parquet(output_path, partitionBy="transaction_date")

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    bronze_df = spark.read.parquet(bronze_path).where(col("transaction_date") == run_date)
    
    # Cast columns to correct types
    bronze_df = bronze_df.withColumn("amount", col("amount").cast(FloatType())) \
                         .withColumn("transaction_date", col("transaction_date").cast(DateType())) \
                         .withColumn("transaction_id", col("transaction_id").cast("string")) \
                        .withColumn("merchant_id", col("merchant_id").cast("string"))
    
    # Filter NULL transaction_id and negative amounts
    bronze_df = bronze_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    latest_txn = Window.partitionBy("transaction_id").orderBy(col("ingestion_timestamp").desc())
    bronze_df = bronze_df.withColumn("rank", row_number().over(latest_txn)) \
                         .filter(col("rank") == 1) \
                         .drop("rank")
    
    # Read merchants and broadcast hint, cache merchants
    merchants_df = spark.read.parquet(merchants_path)
    merchants_df = broadcast(merchants_df)
    merchants_df.cache()
    
    # Join with merchants
    silver_df = bronze_df.join(merchants_df, "merchant_id", "left_outer")
    
    # Add quality_flag column
    silver_df = silver_df.withColumn("quality_flag", 
                                    when(col("merchant_name").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Write Parquet partitioned by date
    silver_df.write.mode("overwrite").parquet(output_path, partitionBy="transaction_date")

def prepare_local_sample_inputs(spark, data_dir):
    os.makedirs(data_dir, exist_ok=True)

    transactions_path = os.path.join(data_dir, "transactions.csv")
    with open(transactions_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=SAMPLE_TRANSACTIONS[0].keys())
        writer.writeheader()
        writer.writerows(SAMPLE_TRANSACTIONS)

    merchants_path = os.path.join(data_dir, "merchants")
    spark.createDataFrame(SAMPLE_MERCHANTS).write.mode("overwrite").parquet(merchants_path)

    return transactions_path, merchants_path


def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("FintechPipeline").getOrCreate()
    
    # Define local paths and run date for this lab run
    local_dir = os.path.join(os.path.dirname(__file__), "local_run")
    input_path, merchants_path = prepare_local_sample_inputs(spark, os.path.join(local_dir, "input"))
    output_path_bronze = os.path.join(local_dir, "bronze")
    output_path_silver = os.path.join(local_dir, "silver")
    run_date = "2024-01-15"
    run_id = "local_run_001"
    
    # Execute bronze stage
    ingest_bronze(spark, input_path, output_path_bronze, run_date, run_id)
    
    # Execute silver stage
    transform_silver(spark, output_path_bronze, merchants_path, output_path_silver, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import avg, col, count, countDistinct, max, min, mode, sum
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate required metrics
    merchant_performance_df = completed_txns.groupBy("merchant_id", "merchant_name", "category", "city", "transaction_date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(col("status").isin("FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write the Gold layer data
    merchant_performance_df.repartition("transaction_date") \
        .write.mode("overwrite").parquet(f"{output_path}/merchant_performance/run_date={run_date}")

def build_customer_ltv(spark, silver_path):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate required metrics
    customer_ltv_df = completed_txns.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    
    # Write the Gold layer data
    customer_ltv_df.write.mode("overwrite").parquet("path_to_gold/customer_ltv")

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Calculate required metrics
    daily_summary_df = silver_df.groupBy("transaction_date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(col("status").isin("FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write the Gold layer data
    daily_summary_df.repartition("transaction_date") \
       .write.mode("overwrite").parquet(f"{output_path}/daily_summary/run_date={run_date}")

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Build the Gold layer components
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path)
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    
    # Write run metadata to JSON
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "components": ["merchant_performance", "customer_ltv", "daily_summary"]
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("GoldPipeline").getOrCreate()
